[package]
name = "handopt_sum_odd_numbers"
version = "0.1.0"
authors = ["Antonin Carette <antonin@carette.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
"num" = "*"
